### PR TITLE
Add support for line mode, NAWS, Status

### PR DESCRIPTION
**Pull request by not-jan**
Hi!
I'm opening this PR to track my progress in implementing line mode in nectar. In addition to that I've also began implementing a few nice-to-have features along the way:

- Negotiate about Window Size (NAWS)
- Status
- Timing Mark
- Remote Flow Control

I'm opening this PR as a draft so that I can receive feed back and track my progress as I go along

### CODE REVIEW

**Comment by robertwayne** [comment]
So far this all looks really good! I only spent a few minutes browsing the diffs, but everything is documented and clean.

I'm not incredibly familiar with the line mode RFC, so I'm deferring a lot to your knowledge here! I'm going to spend some time going over the RFC itself to get an idea of the implementation, but I'm willing to merge once you feel it's ready.

Thanks for your work on this!

**Comment by not-jan** [comment]
Hi! Thank you so much for the initial review. I've rebased my changes upon the new 0.2 version and added a new mode. I'm calling it the character-at-a-time mode similarly to how the original telnet RFC calls it.
This allows nectar to be used in more terminal-like situations where line handling isn't done by nectar itself but rather an underlying application. It is off by default and can be enabled similarly to the sga mode by setting the `message_mode` field on `TelnetCodec` to `false`.

As for the rest of the line mode implementation I'll likely keep it minimal and implement the rest of the de- and encoding but not much of the handling code of the SLCs so most of the logic is I'll be implementing should stay simple and direct.

**Comment by not-jan** [comment]
Okay with todays changes and tests I feel confident for this PR to be ready to be reviewed.

**Comment by robertwayne** [comment]
I'll review and hopefully merge this by the weekend! Been a bit busy with work, so I haven't had much free time this week.

**Comment by robertwayne** [comment]
Alright, this looks good! I did some testing with the new options and everything seems to be working as expected. I'm happy merging this as-is and saving further implementation details for future PRs.

Thanks for working on this!

**Pull request merged**
